### ISSUE TITLE
Is there a way to map all the images?

### ISSUE THREAD

**Issue by astroana** [Ashwinvalento/cartoon-avatar#4]
This is an awesome avatar collection and I would like to use it in my project. I am trying to map all the images in one screen but using map only shows 1 image.

      const toonavatar = require("cartoon-avatar");
      const url = toonavatar.generate_avatar();

     return (
    <div>
      {[url].map((a) => (
        <div><img src={a} /></div>
      ))}
    </div>
     );

**Comment by Ashwinvalento** [comment]
The `generate_avatar` function returns only 1 URL randomly if there are no options provided. You can use the `FEMALE_IMAGE_COUNT`  and `MALE_IMAGE_COUNT` from `cartoon-avatar/config` to get the total images and then use the id option to generate the url.

```
var toonavatar = require('cartoon-avatar');
var config = require('cartoon-avatar/config');

const {FEMALE_IMAGE_COUNT,MALE_IMAGE_COUNT} = config;

 Array.from(Array(FEMALE_IMAGE_COUNT).keys())
          .map((count)=>toonavatar.generate_avatar({"gender":"female","id":count})).map((url)=>{            
            return (
            <img src={url}  alt="logo" />
          )})
```

You can do the similar for all the male images.

Don't forget to add the freepik attribution in you website credits. since these images are taken from freepik.com

**Comment by astroana** [comment]
Thanks a lot. I will try this.
